<?php 

require_once ('MonitorBusquedas.php');

$monitor = new MonitorBusquedas();

//url y puerto del solr de dspace
$PUERTO = "8080";
$SERVIDOR = "http://localhost:" . $PUERTO . "/solr/search/query?";

$consulta = $_REQUEST["consulta"];
$modelo = isset($_REQUEST["modelo"]) ? $_REQUEST["modelo"] : 'Sin modelo';
$plataforma = isset($_REQUEST["plataforma"]) ? $_REQUEST["plataforma"] : 'Sin plataforma';
$facultad = isset($_REQUEST["facultad"]) ? $_REQUEST["facultad"] : 0;

$rawConsulta = $consulta;

$consulta = $SERVIDOR . "wt=json&q=" . urlencode($consulta . " AND withdrawn:false");
   
$idConsulta = $monitor->guardarBusqueda(
  $rawConsulta, 
  $modelo, 
  $plataforma, 
  $facultad );

// $request = curl_init($consulta);
// curl_setopt($request, CURLOPT_HEADER, 0);
// curl_setopt($request, CURLOPT_RETURNTRANSFER, 1);
// $resultado = curl_exec($request);
// curl_close($request);

$resultado = '{
  "responseHeader":{
    "status":0,
    "QTime":1,
    "params":{
      "q":"caliman AND withdrawn:false",
      "wt":"json"}},
  "response":{"numFound":3,"start":0,"docs":[
      {
        "SolrIndexer.lastIndexed":"2016-11-14T18:05:19.615Z",
        "search.uniqueid":"2-1",
        "search.resourcetype":2,
        "search.resourceid":1,
        "handle":"10673/4",
        "location":["m1",
          "l1"],
        "location.comm":["1"],
        "location.coll":["1"],
        "withdrawn":"false",
        "discoverable":"true",
        "author":["Hernandines, Caliman"],
        "author_keyword":["Hernandines, Caliman"],
        "author_ac":["hernandines, caliman\n|||\nHernandines, Caliman"],
        "author_filter":["hernandines, caliman\n|||\nHernandines, Caliman"],
        "dc.contributor.author_hl":["Hernandines, Caliman"],
        "dc.contributor.author_mlt":["Hernandines, Caliman"],
        "dc.contributor.author":["Hernandines, Caliman"],
        "dc.contributor.author_stored":["Hernandines, Caliman\n|||\nnull\n|||\nnull\n|||\nnull\n|||\nnull"],
        "dc.description":["Comments"],
        "dc.description.es_MX":["Comments"],
        "dc.description.abstract_hl":["Introducción a procesamiento de video"],
        "dc.description.abstract":["Introducción a procesamiento de video"],
        "dc.description.abstract.es_MX":["Introducción a procesamiento de video"],
        "dc.description.sponsorship":["Nothing"],
        "dc.description.sponsorship.es_MX":["Nothing"],
        "dc.language.iso":["es"],
        "dc.language.iso.es_MX":["es"],
        "dc.publisher":["Hernandines , Caliman"],
        "dc.publisher.es_MX":["Hernandines , Caliman"],
        "title":["Procesamiento de video"],
        "title_keyword":["Procesamiento de video"],
        "title_ac":["procesamiento de video\n|||\nProcesamiento de video"],
        "dc.title_sort":"Procesamiento de video",
        "dc.title_hl":["Procesamiento de video"],
        "dc.title_mlt":["Procesamiento de video"],
        "dc.title":["Procesamiento de video"],
        "dc.title_stored":["Procesamiento de video\n|||\nnull\n|||\nnull\n|||\nnull\n|||\nes_MX"],
        "dc.title.es_MX":["Procesamiento de video"],
        "dc.title.alternative":["ProcVideo"],
        "dc.title.alternative.es_MX":["ProcVideo"],
        "dc.type":["Presentation"],
        "dc.type.es_MX":["Presentation"],
        "dc.identifier.uri":["http://hdl.handle.net/123456789/3"],
        "dc.date.accessioned_dt":"2016-11-14T18:05:19Z",
        "dc.date.accessioned":["2016-11-14T18:05:19Z"],
        "dc.date.available":["2016-11-14T18:05:19Z"],
        "dateIssued":["2005-11-15"],
        "dateIssued_keyword":["2005-11-15",
          "2005"],
        "dateIssued_ac":["2005-11-15\n|||\n2005-11-15",
          "2005"],
        "dateIssued.year":[2005],
        "dateIssued.year_sort":"2005",
        "dc.date.issued_dt":"2005-11-15T00:00:00Z",
        "dc.date.issued":["2005-11-15"],
        "dc.date.issued_stored":["2005-11-15\n|||\nnull\n|||\nnull\n|||\nnull\n|||\nnull"],
        "publication_grp":["123456789/3"],
        "bi_2_dis_filter":["hernandines, caliman\n|||\nHernandines, Caliman"],
        "bi_2_dis_partial":["Hernandines, Caliman"],
        "bi_2_dis_value_filter":["Hernandines, Caliman"],
        "bi_sort_1_sort":"procesamiento de video",
        "bi_sort_2_sort":"2005-11-15",
        "bi_sort_3_sort":"2016-11-14T18:05:19Z",
        "read":["g0"],
        "_version_":1550997750754050048},
      {
        "SolrIndexer.lastIndexed":"2016-11-14T18:09:12.02Z",
        "search.uniqueid":"2-2",
        "search.resourcetype":2,
        "search.resourceid":2,
        "handle":"10673/5",
        "location":["m1",
          "l1"],
        "location.comm":["1"],
        "location.coll":["1"],
        "withdrawn":"false",
        "discoverable":"true",
        "author":["Hernandines, Caliman"],
        "author_keyword":["Hernandines, Caliman"],
        "author_ac":["hernandines, caliman\n|||\nHernandines, Caliman"],
        "author_filter":["hernandines, caliman\n|||\nHernandines, Caliman"],
        "dc.contributor.author_hl":["Hernandines, Caliman"],
        "dc.contributor.author_mlt":["Hernandines, Caliman"],
        "dc.contributor.author":["Hernandines, Caliman"],
        "dc.contributor.author_stored":["Hernandines, Caliman\n|||\nnull\n|||\nnull\n|||\nnull\n|||\nnull"],
        "dc.language.iso":["es"],
        "dc.language.iso.es_MX":["es"],
        "dc.publisher":["Hernandines , Caliman"],
        "dc.publisher.es_MX":["Hernandines , Caliman"],
        "title":["DetecciÃ³n de cambios en un video"],
        "title_keyword":["DetecciÃ³n de cambios en un video"],
        "title_ac":["detecciÃ³n de cambios en un video\n|||\nDetecciÃ³n de cambios en un video"],
        "dc.title_sort":"DetecciÃ³n de cambios en un video",
        "dc.title_hl":["DetecciÃ³n de cambios en un video"],
        "dc.title_mlt":["DetecciÃ³n de cambios en un video"],
        "dc.title":["DetecciÃ³n de cambios en un video"],
        "dc.title_stored":["DetecciÃ³n de cambios en un video\n|||\nnull\n|||\nnull\n|||\nnull\n|||\nes_MX"],
        "dc.title.es_MX":["DetecciÃ³n de cambios en un video"],
        "dc.title.alternative":["OpticFlow"],
        "dc.title.alternative.es_MX":["OpticFlow"],
        "dc.type":["Presentation"],
        "dc.type.es_MX":["Presentation"],
        "dc.identifier.uri":["http://hdl.handle.net/123456789/4"],
        "dc.date.accessioned_dt":"2016-11-14T18:09:08Z",
        "dc.date.accessioned":["2016-11-14T18:09:08Z"],
        "dc.date.available":["2016-11-14T18:09:08Z"],
        "dateIssued":["2005-11-15"],
        "dateIssued_keyword":["2005-11-15",
          "2005"],
        "dateIssued_ac":["2005-11-15\n|||\n2005-11-15",
          "2005"],
        "dateIssued.year":[2005],
        "dateIssued.year_sort":"2005",
        "dc.date.issued_dt":"2005-11-15T00:00:00Z",
        "dc.date.issued":["2005-11-15"],
        "dc.date.issued_stored":["2005-11-15\n|||\nnull\n|||\nnull\n|||\nnull\n|||\nnull"],
        "publication_grp":["123456789/4"],
        "bi_2_dis_filter":["hernandines, caliman\n|||\nHernandines, Caliman"],
        "bi_2_dis_partial":["Hernandines, Caliman"],
        "bi_2_dis_value_filter":["Hernandines, Caliman"],
        "bi_sort_1_sort":"deteccioÌn de cambios en un video",
        "bi_sort_2_sort":"2005-11-15",
        "bi_sort_3_sort":"2016-11-14T18:09:08Z",
        "read":["g0"],
        "_version_":1550997994380197888},
      {
        "SolrIndexer.lastIndexed":"2016-12-19T18:01:15.051Z",
        "search.uniqueid":"2-3",
        "search.resourcetype":2,
        "search.resourceid":3,
        "handle":"10673/6",
        "location":["m1",
          "l1"],
        "location.comm":["1"],
        "location.coll":["1"],
        "withdrawn":"false",
        "discoverable":"true",
        "author":["caliman, ramires"],
        "author_keyword":["caliman, ramires"],
        "author_ac":["caliman, ramires\n|||\ncaliman, ramires"],
        "author_filter":["caliman, ramires\n|||\ncaliman, ramires"],
        "dc.contributor.author_hl":["caliman, ramires"],
        "dc.contributor.author_mlt":["caliman, ramires"],
        "dc.contributor.author":["caliman, ramires"],
        "dc.contributor.author_stored":["caliman, ramires\n|||\nnull\n|||\nnull\n|||\nnull\n|||\nnull"],
        "dc.identifier.citation":["calimanismo"],
        "dc.identifier.citation.es_MX":["calimanismo"],
        "dc.language.iso":["es"],
        "dc.language.iso.es_MX":["es"],
        "dc.publisher":["redmineros"],
        "dc.publisher.es_MX":["redmineros"],
        "subject":["Research Subject Categories::TECHNOLOGY"],
        "subject_keyword":["Research Subject Categories::TECHNOLOGY",
          "TECHNOLOGY"],
        "subject_ac":["research subject categories::technology\n|||\nResearch Subject Categories::TECHNOLOGY"],
        "subject_tax_0_filter":["technology\n|||\nTECHNOLOGY"],
        "subject_filter":["technology\n|||\nTECHNOLOGY"],
        "dc.subject_mlt":["Research Subject Categories::TECHNOLOGY"],
        "dc.subject":["Research Subject Categories::TECHNOLOGY"],
        "dc.subject.es_MX":["Research Subject Categories::TECHNOLOGY"],
        "title":["sope"],
        "title_keyword":["sope"],
        "title_ac":["sope\n|||\nsope"],
        "dc.title_sort":"sope",
        "dc.title_hl":["sope"],
        "dc.title_mlt":["sope"],
        "dc.title":["sope"],
        "dc.title_stored":["sope\n|||\nnull\n|||\nnull\n|||\nnull\n|||\nes_MX"],
        "dc.title.es_MX":["sope"],
        "dc.title.alternative":["sopes"],
        "dc.title.alternative.es_MX":["sopes"],
        "dc.type":["Animation",
          "Article",
          "Book",
          "Book chapter",
          "Dataset",
          "Learning Object",
          "Image",
          "Image, 3-D",
          "Map",
          "Musical Score",
          "Plan or blueprint",
          "Preprint",
          "Presentation",
          "Recording, acoustical",
          "Recording, musical",
          "Recording, oral",
          "Software",
          "Technical Report",
          "Thesis",
          "Video",
          "Working Paper",
          "Other"],
        "dc.type.es_MX":["Animation",
          "Article",
          "Book",
          "Book chapter",
          "Dataset",
          "Learning Object",
          "Image",
          "Image, 3-D",
          "Map",
          "Musical Score",
          "Plan or blueprint",
          "Preprint",
          "Presentation",
          "Recording, acoustical",
          "Recording, musical",
          "Recording, oral",
          "Software",
          "Technical Report",
          "Thesis",
          "Video",
          "Working Paper",
          "Other"],
        "dc.identifier.uri":["http://hdl.handle.net/123456789/5"],
        "dc.date.accessioned_dt":"2016-12-19T18:01:14Z",
        "dc.date.accessioned":["2016-12-19T18:01:14Z"],
        "dc.date.available":["2016-12-19T18:01:14Z"],
        "dateIssued":["2009-05-18"],
        "dateIssued_keyword":["2009-05-18",
          "2009"],
        "dateIssued_ac":["2009-05-18\n|||\n2009-05-18",
          "2009"],
        "dateIssued.year":[2009],
        "dateIssued.year_sort":"2009",
        "dc.date.issued_dt":"2009-05-18T00:00:00Z",
        "dc.date.issued":["2009-05-18"],
        "dc.date.issued_stored":["2009-05-18\n|||\nnull\n|||\nnull\n|||\nnull\n|||\nnull"],
        "publication_grp":["123456789/5"],
        "bi_2_dis_filter":["caliman, ramires\n|||\ncaliman, ramires"],
        "bi_2_dis_partial":["caliman, ramires"],
        "bi_2_dis_value_filter":["caliman, ramires"],
        "bi_4_dis_filter":["research subject categories::technology\n|||\nResearch Subject Categories::TECHNOLOGY"],
        "bi_4_dis_partial":["Research Subject Categories::TECHNOLOGY"],
        "bi_4_dis_value_filter":["Research Subject Categories::TECHNOLOGY"],
        "bi_sort_1_sort":"sope",
        "bi_sort_2_sort":"2009-05-18",
        "bi_sort_3_sort":"2016-12-19T18:01:14Z",
        "read":["g0"],
        "_version_":1554168388185489408}]
  }}';



$monitor->guardarResultado($idConsulta, $resultado);
header("Content-Type: application/json");
echo $resultado;